# sample_config.yaml

utils:
  seed: 123
  torch_num_threads: 10

task:
  name: 'AMP'
  type: AMP # type: cdfg or dfg
  target: pm # different target prediction
  processed_folder: './data_processed/'
  divide_seed: default #set as default or a seed
  raw_data_path: './data_raw/AMP/'
  data_processor: AMPDataProcessor

train:
  batch_size: 64
  epoch: 300
  optimizer: Adam
  scheduler: 
    name: StepLR
    step_size: 100
    gamma: 0.95
  lr : 0.0021
  criterion: MSE
  wandb: 1
  train_files: './train_files/'
  directed: 1

model: 
  name: BIGINE
  hidden_dim: 288
  num_layers: 4
  node_input_dim: 7
  edge_input_dim: 2
  dropout: 0.2
  mlp_out:
    num_layer: 4
