model:
  pe_file_name: lap_n_spe
  pe_type: lap
  pe_strategy: variant
  lap_pe_dim_input: 10
  lap_pe_dim_output: 10
  se_pe_dim_input: 0
  se_pe_dim_output: 0
  
  eigval_encoder:
    in: 1
    hidden: 32
    out: 8
    num_layer: 3

  pe_embedder:
    name: spe
    norm: ln # layer norm. Remove it means no normalization
    k_hops: 2 # number of layers of gnn encoder for node-level spe
